### ISSUE TITLE
Yapay Zeka, Makine Ogrenmesi ve Goruntu Isleme Ders Notlari

### ISSUE THREAD

**Issue by ayyucedemirbas** [AhmetEkmell/Ders-Notlari#1]
Bu bir issue degil aslinda, ders notu linklerini ekliyorum, benden clonelayarak repoya ekleyebilirsiniz. (PR atamiyorum, repoyu lokale clonelamam gerek fakat internet paketim az ve repo cok buyuk)

Yapay zeka: https://github.com/ayyucedemirbas/yapay-zeka-ders-notlari
Makine ogrenmesi: https://github.com/ayyucedemirbas/Machine_Learning_LectureNotes
Goruntu isleme: https://github.com/ayyucedemirbas/Goruntu-Isleme-Ders-Notlari

Bu arada repodaki sinyaller sistemler notlari bana ait, asiri mutlu oldum gorunce.

**Comment by AhmetEkmell** [comment]
Çok teşekkürler Ayyüce yeni gördüm yazdıklarını.
Kusura bakma senin notların olduğunu bilmiyordum bilseydim sorardım sana :) 
Notların ve katkıların için teşekkürler umarım arkadaşlarımız faydalanabilirler :)
Müsait bir vakitte senin notları da eklemiş olacağım.
