### ISSUE TITLE
Ders Notları

### ISSUE THREAD

**Issue by Genc** [AhmetEkmell/Ders-Notlari#4]
Selamlar,

Elimde hemen hemen tüm derslere ait ders notları/örnekleri mevcut, ancak toparlayıp & kategorize etmeye imkan bulamadım. Başlamıştım ancak baktım yetiştiremiyorum, ihtiyacı olan birileri vardır daha fazla bekletmek istemedim.

Drive linki olarak paylaşıyorum, buradan repoya eklemeler yapabilirsiniz.

https://drive.google.com/file/d/1QP0dZVPzMPCEGA0-pxrdr5ptjk8kRZTE/view?usp=sharing

**Comment by AhmetEkmell** [comment]
Çok teşekkürler katkılarınız için en kısa zamanda eklemeleri yapmış olacağım.

**Comment by AhmetEkmell** [comment]
Drive dosya boyutu çok büyükmüş :) Sanırım senin Drive linkin hep burada kalsa daha güzel olacak :) Tekrar Çok teşekkürler repoya katkılarınız için @Genc  👍

**Comment by Genc** [comment]
Tamamdır 👍 Rica ederim @AhmetEkmell 😃
